"""Added Comparison model

Revision ID: ec11ae45c4e7
Revises: 
Create Date: 2023-09-17 17:34:49.561665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec11ae45c4e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comparison', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comparison_notes', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('selected_run_ids', sa.Text(), nullable=True))

    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mlflow_run_id_notes', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.drop_column('mlflow_run_id_notes')

    with op.batch_alter_table('comparison', schema=None) as batch_op:
        batch_op.drop_column('selected_run_ids')
        batch_op.drop_column('comparison_notes')

    # ### end Alembic commands ###
